-- =============================================
-- REALITY RADIO NETWORK - DATA MIGRATION
-- Execute este SQL no Supabase SQL Editor após criar o schema
-- Gerado automaticamente em: 2025-12-15
-- =============================================

-- IMPORTANTE: Execute este arquivo APÓS o schema.sql
-- Este arquivo contém todos os dados de artistas, álbuns, singles e blogs

-- =============================================
-- LIMPAR DADOS EXISTENTES (OPCIONAL)
-- Descomente se quiser limpar antes de inserir
-- =============================================
-- TRUNCATE TABLE singles CASCADE;
-- TRUNCATE TABLE tracks CASCADE;
-- TRUNCATE TABLE albums CASCADE;
-- TRUNCATE TABLE artists CASCADE;
-- TRUNCATE TABLE blogs CASCADE;

-- =============================================
-- 1. INSERIR ARTISTAS
-- =============================================
INSERT INTO artists (slug, name, genre, bio, image, accent_color, social_links, created_at, updated_at)
VALUES
  (
    'johnathan-gold',
    'Johnathan Gold & Guilded Hearts',
    'Country / Americana',
    'Johnathan Gold brings heartland truths with raw emotion, balancing modern country roots and bold lyrical honesty.',
    '/Johnathan Gold.png',
    'purple',
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  (
    'kaira-heartfelt',
    'Kaira Heartfelt',
    'Pop / Electronic',
    'Kaira Heartfelt delivers emotionally charged pop anthems with electronic undertones that resonate with the soul.',
    '/Kaira Heartfelt.png',
    'pink',
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  (
    'mathew-cage',
    'Mathew Cage',
    'Rock / Alternative',
    'Mathew Cage delivers powerful rock anthems that challenge conventions and speak truth to power.',
    '/Mathew Cage.png',
    'red',
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  (
    'chronix',
    'Chronix',
    'Electronic / Synthwave',
    'Chronix creates immersive electronic soundscapes that transport listeners through time and space.',
    '/Chronix.png',
    'indigo',
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  (
    'daina-vein',
    'Daina Vein',
    'Electronic / Industrial',
    'Daina Vein delivers explosive electronic intensity with raw emotional power. Each track ignites with industrial beats and ethereal vocals.',
    '/Daina Vein.png',
    'red',
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  genre = EXCLUDED.genre,
  bio = EXCLUDED.bio,
  image = EXCLUDED.image,
  accent_color = EXCLUDED.accent_color,
  social_links = EXCLUDED.social_links,
  updated_at = NOW();

-- =============================================
-- 2. INSERIR ÁLBUNS
-- =============================================
INSERT INTO albums (slug, title, artist_id, artist_name, artist_slug, genre, year, duration, digital_price, physical_price, catalog, image, description, digital_buy_link, physical_buy_link, accent_color, featured, streaming_links, created_at, updated_at)
VALUES
  (
    'americas-changed',
    'America''s Changed',
    (SELECT id FROM artists WHERE slug = 'johnathan-gold'),
    'Johnathan Gold',
    'johnathan-gold',
    'Country / Americana',
    2025,
    '38:00',
    8.99,
    14.99,
    'RRN-JG-AC',
    '/America''s Changed.png',
    'A powerful country album about the changing face of America',
    'https://square.link/u/8vYPUPDl',
    'https://square.link/u/NB6AhAuq',
    'purple',
    true,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  (
    'heartfelt-rebellion',
    'Heartfelt Rebellion',
    (SELECT id FROM artists WHERE slug = 'kaira-heartfelt'),
    'Kaira Heartfelt',
    'kaira-heartfelt',
    'Country-Pop',
    2025,
    '52:00',
    8.99,
    14.99,
    'RRN-KH-HR',
    '/Heartfelt Rebellion.svg',
    'A rebellious country-pop journey through love and independence',
    'https://square.link/u/hpERvq5a',
    'https://square.link/u/I0y2neFk',
    'pink',
    true,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  (
    'golden-heartbreak',
    'Golden Heartbreak',
    (SELECT id FROM artists WHERE slug = 'johnathan-gold'),
    'Johnathan Gold',
    'johnathan-gold',
    'Country / Americana',
    2025,
    '78:00',
    12.99,
    24.99,
    'RRN-JG-GH',
    '/Golden Heartbreak.png',
    'A double album of heartbreak and redemption',
    'https://square.link/u/M5p4wqPq',
    'https://square.link/u/Fxnf3Vdv',
    'purple',
    true,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  (
    'barefoot-supernova',
    'Barefoot Supernova',
    (SELECT id FROM artists WHERE slug = 'johnathan-gold'),
    'Johnathan Gold',
    'johnathan-gold',
    'Country / Rock',
    2025,
    '56:00',
    8.99,
    14.99,
    'RRN-JG-BS',
    '/Barefoot Supernova.png',
    'An explosive mix of country and rock',
    'https://square.link/u/gu45gzwi',
    'https://square.link/u/Zk8fGBle',
    'purple',
    true,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  (
    'stellar-love',
    'Stellar Love',
    (SELECT id FROM artists WHERE slug = 'kaira-heartfelt'),
    'Kaira Heartfelt',
    'kaira-heartfelt',
    'Country-Pop / Romantic Country',
    2025,
    '40:23',
    8.99,
    14.99,
    'RRN-KH-SL',
    '/Stellar Love.svg',
    'A clashing of love, lust, and heartbreak',
    'https://square.link/u/Txr1N34B',
    'https://square.link/u/M2p3RQNg',
    'pink',
    true,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  (
    'shattered-peaces',
    'Shattered Peaces',
    (SELECT id FROM artists WHERE slug = 'mathew-cage'),
    'Mathew Cage',
    'mathew-cage',
    'Alt Rock / Emotional Rock',
    2025,
    '47:00',
    8.99,
    19.99,
    'RRN-MC-SP',
    '/Shattered Peaces.png',
    'Alt rock journey through emotion, resilience, and identity',
    'https://square.link/u/L2CIvC40',
    'https://square.link/u/02cCRDCl',
    'red',
    true,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  (
    'high-hit',
    'High Hit',
    (SELECT id FROM artists WHERE slug = 'mathew-cage'),
    'Mathew Cage',
    'mathew-cage',
    'Alt Rock / Protest Rock',
    2025,
    '41:40',
    8.99,
    14.99,
    'RRN-MC-HH',
    '/High Hit.svg',
    'A multi-meaning album of fire and resolve. A voice for the people.',
    'https://square.link/u/5dXvGxd4',
    'https://square.link/u/wuLEwHwX',
    'red',
    true,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  (
    'decend',
    'Descend',
    (SELECT id FROM artists WHERE slug = 'chronix'),
    'Chronix',
    'chronix',
    'Experimental Electronic / Dark Ambient',
    2025,
    '44:03',
    8.99,
    14.99,
    'RRN-CHX-DEC',
    '/Decend.svg',
    'The mind descends into darkness so easily, but sometimes it also grows in the darkness',
    'https://square.link/u/Pil3gVkP',
    'https://square.link/u/f9VJJDnj',
    'indigo',
    true,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  (
    'warmth-of-chaos',
    'Warmth of Chaos',
    (SELECT id FROM artists WHERE slug = 'daina-vein'),
    'Daina Vein',
    'daina-vein',
    'Electronic / Industrial',
    2025,
    '28:45',
    8.99,
    14.99,
    'RRN-DV-WOC',
    '/Warmth of Chaos.svg',
    'An intense journey through electronic chaos and warmth',
    '',
    '',
    'red',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  )
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  artist_name = EXCLUDED.artist_name,
  artist_slug = EXCLUDED.artist_slug,
  genre = EXCLUDED.genre,
  year = EXCLUDED.year,
  duration = EXCLUDED.duration,
  digital_price = EXCLUDED.digital_price,
  physical_price = EXCLUDED.physical_price,
  catalog = EXCLUDED.catalog,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  digital_buy_link = EXCLUDED.digital_buy_link,
  physical_buy_link = EXCLUDED.physical_buy_link,
  accent_color = EXCLUDED.accent_color,
  featured = EXCLUDED.featured,
  streaming_links = EXCLUDED.streaming_links,
  updated_at = NOW();

-- =============================================
-- 3. INSERIR SINGLES
-- =============================================
INSERT INTO singles (slug, title, artist_id, artist_name, artist_slug, album_id, album_title, album_slug, genre, year, duration, price, catalog, description, buy_link, preview_url, image, accent_color, featured, streaming_links, created_at, updated_at)
VALUES
  -- America's Changed (Single)
  (
    'americas-changed',
    'America''s Changed',
    (SELECT id FROM artists WHERE slug = 'johnathan-gold'),
    'Johnathan Gold',
    'johnathan-gold',
    (SELECT id FROM albums WHERE slug = 'americas-changed'),
    'America''s Changed',
    'americas-changed',
    'Country',
    2025,
    '3:45',
    0.99,
    'RRN-JG-AC-01',
    'Title track from the America''s Changed album',
    'https://square.link/u/cLvZVxhh',
    NULL,
    NULL,
    'purple',
    true,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Back When We Fell
  (
    'back-when-we-fell',
    'Back When We Fell',
    (SELECT id FROM artists WHERE slug = 'johnathan-gold'),
    'Johnathan Gold',
    'johnathan-gold',
    NULL,
    NULL,
    NULL,
    'Country',
    2025,
    '3:38',
    0.99,
    'RRN-JG-BWWF',
    'A nostalgic country ballad',
    'https://square.link/u/xhxPVJDn',
    NULL,
    NULL,
    'purple',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Barefoot Change
  (
    'barefoot-change',
    'Barefoot Change',
    (SELECT id FROM artists WHERE slug = 'johnathan-gold'),
    'Johnathan Gold',
    'johnathan-gold',
    (SELECT id FROM albums WHERE slug = 'barefoot-supernova'),
    'Barefoot Supernova',
    'barefoot-supernova',
    'Country',
    2025,
    '3:52',
    0.99,
    'RRN-JG-BC',
    'From the Barefoot Supernova album',
    'https://square.link/u/56avqyRz',
    NULL,
    NULL,
    'purple',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Chaos Country
  (
    'chaos-country',
    'Chaos Country',
    (SELECT id FROM artists WHERE slug = 'johnathan-gold'),
    'Johnathan Gold',
    'johnathan-gold',
    NULL,
    NULL,
    NULL,
    'Country',
    2025,
    '3:45',
    0.99,
    'RRN-JG-CC',
    'High-energy country track',
    'https://square.link/u/0sM7bXR7',
    NULL,
    NULL,
    'purple',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Chronicles
  (
    'chronicles',
    'Chronicles',
    (SELECT id FROM artists WHERE slug = 'mathew-cage'),
    'Mathew Cage',
    'mathew-cage',
    (SELECT id FROM albums WHERE slug = 'high-hit'),
    'High Hit',
    'high-hit',
    'Alt Rock',
    2025,
    '4:05',
    0.99,
    'RRN-MC-CHR',
    'From the High Hit album',
    'https://square.link/u/kEfKJCIE',
    NULL,
    NULL,
    'red',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- City Girl
  (
    'city-girl',
    'City Girl',
    (SELECT id FROM artists WHERE slug = 'johnathan-gold'),
    'Johnathan Gold',
    'johnathan-gold',
    NULL,
    NULL,
    NULL,
    'Country',
    2025,
    '3:42',
    0.99,
    'RRN-JG-CG',
    'A country song about city life',
    'https://square.link/u/ejBiKuM6',
    NULL,
    NULL,
    'purple',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Country Bonfire
  (
    'country-bonfire',
    'Country Bonfire',
    (SELECT id FROM artists WHERE slug = 'johnathan-gold'),
    'Johnathan Gold',
    'johnathan-gold',
    NULL,
    NULL,
    NULL,
    'Country',
    2025,
    '3:55',
    0.99,
    'RRN-JG-CB',
    'A warm country anthem',
    'https://square.link/u/UGKRSozd',
    NULL,
    NULL,
    'purple',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Country Girl
  (
    'country-girl',
    'Country Girl',
    (SELECT id FROM artists WHERE slug = 'johnathan-gold'),
    'Johnathan Gold',
    'johnathan-gold',
    NULL,
    NULL,
    NULL,
    'Country',
    2025,
    '3:48',
    0.99,
    'RRN-JG-CGI',
    'A tribute to country girls',
    'https://square.link/u/qF1jAHCW',
    NULL,
    NULL,
    'purple',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Country Looks
  (
    'country-looks',
    'Country Looks',
    (SELECT id FROM artists WHERE slug = 'johnathan-gold'),
    'Johnathan Gold',
    'johnathan-gold',
    NULL,
    NULL,
    NULL,
    'Country',
    2025,
    '3:35',
    0.99,
    'RRN-JG-CL',
    'A country love song',
    'https://square.link/u/zMM8N6F9',
    NULL,
    NULL,
    'purple',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Country Lovin'
  (
    'country-lovin',
    'Country Lovin''',
    (SELECT id FROM artists WHERE slug = 'johnathan-gold'),
    'Johnathan Gold',
    'johnathan-gold',
    NULL,
    NULL,
    NULL,
    'Country',
    2025,
    '3:42',
    0.99,
    'RRN-JG-CLV',
    'A romantic country track',
    'https://square.link/u/TLR0FVsA',
    NULL,
    NULL,
    'purple',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Drown it Out
  (
    'drown-it-out',
    'Drown it Out',
    (SELECT id FROM artists WHERE slug = 'mathew-cage'),
    'Mathew Cage',
    'mathew-cage',
    (SELECT id FROM albums WHERE slug = 'high-hit'),
    'High Hit',
    'high-hit',
    'Alt Rock',
    2025,
    '3:52',
    0.99,
    'RRN-MC-DIO',
    'From the High Hit album',
    'https://square.link/u/KCOOq0Jr',
    NULL,
    NULL,
    'red',
    true,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Echoes of the Cage
  (
    'echoes-of-the-cage',
    'Echoes of the Cage',
    (SELECT id FROM artists WHERE slug = 'mathew-cage'),
    'Mathew Cage',
    'mathew-cage',
    (SELECT id FROM albums WHERE slug = 'shattered-peaces'),
    'Shattered Peaces',
    'shattered-peaces',
    'Alt Rock',
    2025,
    '4:28',
    0.99,
    'RRN-MC-EOTC',
    'From the Shattered Peaces album',
    'https://square.link/u/zwQRJCwe',
    NULL,
    NULL,
    'red',
    true,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Evil Love
  (
    'evil-love',
    'Evil Love',
    (SELECT id FROM artists WHERE slug = 'kaira-heartfelt'),
    'Kaira Heartfelt',
    'kaira-heartfelt',
    NULL,
    NULL,
    NULL,
    'Country-Pop',
    2025,
    '3:38',
    0.99,
    'RRN-KH-EL',
    'A dark romantic ballad',
    'https://square.link/u/hZjHW3Wk',
    NULL,
    NULL,
    'pink',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Fallen Dust
  (
    'fallen-dust',
    'Fallen Dust',
    (SELECT id FROM artists WHERE slug = 'mathew-cage'),
    'Mathew Cage',
    'mathew-cage',
    (SELECT id FROM albums WHERE slug = 'high-hit'),
    'High Hit',
    'high-hit',
    'Alt Rock',
    2025,
    '4:28',
    0.99,
    'RRN-MC-FD',
    'From the High Hit album',
    'https://square.link/u/zsgL3N5e',
    NULL,
    NULL,
    'red',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Fallen Flag
  (
    'fallen-flag',
    'Fallen Flag',
    (SELECT id FROM artists WHERE slug = 'mathew-cage'),
    'Mathew Cage',
    'mathew-cage',
    (SELECT id FROM albums WHERE slug = 'shattered-peaces'),
    'Shattered Peaces',
    'shattered-peaces',
    'Alt Rock',
    2025,
    '5:05',
    0.99,
    'RRN-MC-FF',
    'From the Shattered Peaces album',
    'https://square.link/u/VEMs3Tdc',
    NULL,
    NULL,
    'red',
    true,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Forgotten Sons
  (
    'forgotten-sons',
    'Forgotten Sons',
    (SELECT id FROM artists WHERE slug = 'johnathan-gold'),
    'Johnathan Gold',
    'johnathan-gold',
    NULL,
    NULL,
    NULL,
    'Country',
    2025,
    '4:12',
    0.99,
    'RRN-JG-FS',
    'A powerful country ballad',
    'https://square.link/u/lbWBcfEw',
    NULL,
    NULL,
    'purple',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Fractured Signal
  (
    'fractured-signal',
    'Fractured Signal',
    (SELECT id FROM artists WHERE slug = 'mathew-cage'),
    'Mathew Cage',
    'mathew-cage',
    (SELECT id FROM albums WHERE slug = 'shattered-peaces'),
    'Shattered Peaces',
    'shattered-peaces',
    'Alt Rock',
    2025,
    '4:02',
    0.99,
    'RRN-MC-FS',
    'From the Shattered Peaces album',
    'https://square.link/u/2OwcTGU3',
    NULL,
    NULL,
    'red',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Gas Station Prayers
  (
    'gas-station-prayers',
    'Gas Station Prayers',
    (SELECT id FROM artists WHERE slug = 'johnathan-gold'),
    'Johnathan Gold',
    'johnathan-gold',
    NULL,
    NULL,
    NULL,
    'Country',
    2025,
    '3:55',
    0.99,
    'RRN-JG-GSP',
    'A reflective country track',
    'https://square.link/u/uZ3CXyNi',
    NULL,
    NULL,
    'purple',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- God Blessed the Silent Ones
  (
    'god-blessed-the-silent-ones',
    'God Blessed the Silent Ones',
    (SELECT id FROM artists WHERE slug = 'johnathan-gold'),
    'Johnathan Gold',
    'johnathan-gold',
    NULL,
    NULL,
    NULL,
    'Country',
    2025,
    '4:08',
    0.99,
    'RRN-JG-GBTSO',
    'A spiritual country anthem',
    'https://square.link/u/4yDcOqMs',
    NULL,
    NULL,
    'purple',
    true,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Goodbye Mainstreet
  (
    'goodbye-mainstreet',
    'Goodbye Mainstreet',
    (SELECT id FROM artists WHERE slug = 'johnathan-gold'),
    'Johnathan Gold',
    'johnathan-gold',
    NULL,
    NULL,
    NULL,
    'Country',
    2025,
    '3:48',
    0.99,
    'RRN-JG-GM',
    'A farewell to small town life',
    'https://square.link/u/yWtFJNzX',
    NULL,
    NULL,
    'purple',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Hate No More
  (
    'hate-no-more',
    'Hate No More',
    (SELECT id FROM artists WHERE slug = 'chronix'),
    'Chronix',
    'chronix',
    (SELECT id FROM albums WHERE slug = 'decend'),
    'Descend',
    'decend',
    'Electronic',
    2025,
    '4:22',
    0.99,
    'RRN-CHX-HNM',
    'From the Descend album',
    'https://square.link/u/GoUQUJXA',
    NULL,
    NULL,
    'indigo',
    true,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Heartfelt Rebellion (Single)
  (
    'heartfelt-rebellion',
    'Heartfelt Rebellion',
    (SELECT id FROM artists WHERE slug = 'kaira-heartfelt'),
    'Kaira Heartfelt',
    'kaira-heartfelt',
    (SELECT id FROM albums WHERE slug = 'heartfelt-rebellion'),
    'Heartfelt Rebellion',
    'heartfelt-rebellion',
    'Country-Pop',
    2025,
    '3:52',
    0.99,
    'RRN-KH-HR-01',
    'Title track from the Heartfelt Rebellion album',
    'https://square.link/u/jjD1AEXz',
    NULL,
    NULL,
    'pink',
    true,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Love Killer
  (
    'love-killer',
    'Love Killer',
    (SELECT id FROM artists WHERE slug = 'kaira-heartfelt'),
    'Kaira Heartfelt',
    'kaira-heartfelt',
    (SELECT id FROM albums WHERE slug = 'stellar-love'),
    'Stellar Love',
    'stellar-love',
    'Country-Pop',
    2025,
    '3:45',
    0.99,
    'RRN-KH-LK',
    'From the Stellar Love album',
    'https://square.link/u/YkZwnMzA',
    NULL,
    NULL,
    'pink',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Lovestruck
  (
    'lovestruck',
    'Lovestruck',
    (SELECT id FROM artists WHERE slug = 'kaira-heartfelt'),
    'Kaira Heartfelt',
    'kaira-heartfelt',
    NULL,
    NULL,
    NULL,
    'Country-Pop',
    2025,
    '3:38',
    0.99,
    'RRN-KH-LS',
    'A romantic country-pop hit',
    'https://square.link/u/mKf2NJWP',
    NULL,
    NULL,
    'pink',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Lustful Love
  (
    'lustful-love',
    'Lustful Love',
    (SELECT id FROM artists WHERE slug = 'kaira-heartfelt'),
    'Kaira Heartfelt',
    'kaira-heartfelt',
    (SELECT id FROM albums WHERE slug = 'stellar-love'),
    'Stellar Love',
    'stellar-love',
    'Country-Pop',
    2025,
    '3:28',
    0.99,
    'RRN-KH-LL',
    'From the Stellar Love album',
    'https://square.link/u/7Z7NtdOx',
    NULL,
    NULL,
    'pink',
    true,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Mark Me Down
  (
    'mark-me-down',
    'Mark Me Down',
    (SELECT id FROM artists WHERE slug = 'chronix'),
    'Chronix',
    'chronix',
    (SELECT id FROM albums WHERE slug = 'decend'),
    'Descend',
    'decend',
    'Electronic',
    2025,
    '4:48',
    0.99,
    'RRN-CHX-MMD',
    'From the Descend album',
    'https://square.link/u/1vzafXZ0',
    NULL,
    NULL,
    'indigo',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- One Drink
  (
    'one-drink',
    'One Drink',
    (SELECT id FROM artists WHERE slug = 'mathew-cage'),
    'Mathew Cage',
    'mathew-cage',
    (SELECT id FROM albums WHERE slug = 'high-hit'),
    'High Hit',
    'high-hit',
    'Alt Rock',
    2025,
    '3:45',
    0.99,
    'RRN-MC-OD',
    'From the High Hit album',
    'https://square.link/u/POxETfEH',
    NULL,
    NULL,
    'red',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Power of the Few
  (
    'power-of-the-few',
    'Power of the Few',
    (SELECT id FROM artists WHERE slug = 'chronix'),
    'Chronix',
    'chronix',
    (SELECT id FROM albums WHERE slug = 'decend'),
    'Descend',
    'decend',
    'Electronic',
    2025,
    '4:38',
    0.99,
    'RRN-CHX-POTF',
    'From the Descend album',
    'https://square.link/u/gILHmo6H',
    NULL,
    NULL,
    'indigo',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Rags No More
  (
    'rags-no-more',
    'Rags No More',
    (SELECT id FROM artists WHERE slug = 'chronix'),
    'Chronix',
    'chronix',
    (SELECT id FROM albums WHERE slug = 'decend'),
    'Descend',
    'decend',
    'Electronic',
    2025,
    '4:05',
    0.99,
    'RRN-CHX-RNM',
    'From the Descend album',
    'https://square.link/u/tW4GpZEt',
    NULL,
    NULL,
    'indigo',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Scraps
  (
    'scraps',
    'Scraps',
    (SELECT id FROM artists WHERE slug = 'mathew-cage'),
    'Mathew Cage',
    'mathew-cage',
    (SELECT id FROM albums WHERE slug = 'high-hit'),
    'High Hit',
    'high-hit',
    'Alt Rock',
    2025,
    '4:12',
    0.99,
    'RRN-MC-SCR',
    'From the High Hit album',
    'https://square.link/u/Nk4Sjd9j',
    NULL,
    NULL,
    'red',
    true,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Screens
  (
    'screens',
    'Screens',
    (SELECT id FROM artists WHERE slug = 'johnathan-gold'),
    'Johnathan Gold',
    'johnathan-gold',
    NULL,
    NULL,
    NULL,
    'Country',
    2025,
    '3:45',
    0.99,
    'RRN-JG-SCR',
    'A commentary on modern life',
    'https://square.link/u/XnOjVtYd',
    NULL,
    NULL,
    'purple',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- She Wore Red, I Wore Blue
  (
    'she-wore-red-i-wore-blue',
    'She Wore Red, I Wore Blue',
    (SELECT id FROM artists WHERE slug = 'johnathan-gold'),
    'Johnathan Gold',
    'johnathan-gold',
    NULL,
    NULL,
    NULL,
    'Country',
    2025,
    '3:52',
    0.99,
    'RRN-JG-SWRIWB',
    'A colorful country love story',
    'https://square.link/u/1bqFtJH3',
    NULL,
    NULL,
    'purple',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Small Town Supernova
  (
    'small-town-supernova',
    'Small Town Supernova',
    (SELECT id FROM artists WHERE slug = 'johnathan-gold'),
    'Johnathan Gold',
    'johnathan-gold',
    (SELECT id FROM albums WHERE slug = 'barefoot-supernova'),
    'Barefoot Supernova',
    'barefoot-supernova',
    'Country',
    2025,
    '4:02',
    0.99,
    'RRN-JG-STS',
    'From the Barefoot Supernova album',
    'https://square.link/u/0o1u4wKc',
    NULL,
    NULL,
    'purple',
    true,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Starting Line
  (
    'starting-line',
    'Starting Line',
    (SELECT id FROM artists WHERE slug = 'chronix'),
    'Chronix',
    'chronix',
    (SELECT id FROM albums WHERE slug = 'decend'),
    'Descend',
    'decend',
    'Electronic',
    2025,
    '4:12',
    0.99,
    'RRN-CHX-SL',
    'From the Descend album',
    'https://square.link/u/EQCSb9Zm',
    NULL,
    NULL,
    'indigo',
    true,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Take My Love
  (
    'take-my-love',
    'Take My Love',
    (SELECT id FROM artists WHERE slug = 'kaira-heartfelt'),
    'Kaira Heartfelt',
    'kaira-heartfelt',
    (SELECT id FROM albums WHERE slug = 'stellar-love'),
    'Stellar Love',
    'stellar-love',
    'Country-Pop',
    2025,
    '3:18',
    0.99,
    'RRN-KH-TML',
    'From the Stellar Love album',
    'https://square.link/u/8kANPQUF',
    NULL,
    NULL,
    'pink',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- The Line Was Crossed
  (
    'the-line-was-crossed',
    'The Line Was Crossed',
    (SELECT id FROM artists WHERE slug = 'mathew-cage'),
    'Mathew Cage',
    'mathew-cage',
    (SELECT id FROM albums WHERE slug = 'shattered-peaces'),
    'Shattered Peaces',
    'shattered-peaces',
    'Alt Rock',
    2025,
    '3:58',
    0.99,
    'RRN-MC-TLWC',
    'From the Shattered Peaces album',
    'https://square.link/u/VOSlMOow',
    NULL,
    NULL,
    'red',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- The Stars Above
  (
    'the-stars-above',
    'The Stars Above',
    (SELECT id FROM artists WHERE slug = 'kaira-heartfelt'),
    'Kaira Heartfelt',
    'kaira-heartfelt',
    (SELECT id FROM albums WHERE slug = 'stellar-love'),
    'Stellar Love',
    'stellar-love',
    'Country-Pop',
    2025,
    '3:52',
    0.99,
    'RRN-KH-TSA',
    'From the Stellar Love album',
    'https://square.link/u/1vJh1PwJ',
    NULL,
    NULL,
    'pink',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- Tractor Heart
  (
    'tractor-heart',
    'Tractor Heart',
    (SELECT id FROM artists WHERE slug = 'johnathan-gold'),
    'Johnathan Gold',
    'johnathan-gold',
    NULL,
    NULL,
    NULL,
    'Country',
    2025,
    '3:48',
    0.99,
    'RRN-JG-TH',
    'A heartfelt country track',
    'https://square.link/u/HkMgTQbV',
    NULL,
    NULL,
    'purple',
    false,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  ),
  -- World of Gold
  (
    'world-of-gold',
    'World of Gold',
    (SELECT id FROM artists WHERE slug = 'mathew-cage'),
    'Mathew Cage',
    'mathew-cage',
    (SELECT id FROM albums WHERE slug = 'shattered-peaces'),
    'Shattered Peaces',
    'shattered-peaces',
    'Alt Rock',
    2025,
    '3:06',
    0.99,
    'RRN-MC-WOG',
    'From the Shattered Peaces album',
    'https://square.link/u/ioeRiwvN',
    NULL,
    NULL,
    'red',
    true,
    '{}',
    '2025-01-01T00:00:00.000Z',
    '2025-01-01T00:00:00.000Z'
  )
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  artist_name = EXCLUDED.artist_name,
  artist_slug = EXCLUDED.artist_slug,
  album_title = EXCLUDED.album_title,
  album_slug = EXCLUDED.album_slug,
  genre = EXCLUDED.genre,
  year = EXCLUDED.year,
  duration = EXCLUDED.duration,
  price = EXCLUDED.price,
  catalog = EXCLUDED.catalog,
  description = EXCLUDED.description,
  buy_link = EXCLUDED.buy_link,
  preview_url = EXCLUDED.preview_url,
  image = EXCLUDED.image,
  accent_color = EXCLUDED.accent_color,
  featured = EXCLUDED.featured,
  streaming_links = EXCLUDED.streaming_links,
  updated_at = NOW();

-- =============================================
-- 4. INSERIR BLOGS
-- =============================================
INSERT INTO blogs (slug, title, content, excerpt, author, image, tags, published, published_at, created_at, updated_at)
VALUES
  (
    'welcome-reality-radio-network',
    'Welcome to Reality Radio Network',
    E'Welcome to Reality Radio Network! We''re excited to introduce your new source for innovative AI-generated music.

## Our Mission

At Reality Radio Network, we believe that artificial intelligence doesn''t replace human creativity, but amplifies it. Our goal is to create unique musical experiences that blend cutting-edge technology with artistic expression.

Our focus is on:

- **Original songs** generated by cutting-edge AI technology
- **Unique personas** with distinct musical styles and personalities  
- **24/7 broadcasting** so you can listen anywhere, anytime
- **Constant innovation** in every beat and melody

## What Makes Reality Radio Special?

### Total Transparency

We''re 100% transparent about our use of AI. Every song is clearly identified as AI-generated, ensuring you always know what you''re listening to.

### Fair Licensing

We offer flexible licensing options for content creators, businesses, and film producers who want to use our music in their projects.

### Persona Program

Each persona in our network has its own unique musical identity, creating a diverse and engaging listening experience across multiple genres.

## Start Exploring

Ready to discover the future of music? Here''s how to get started:

- **Listen Live**: Tune into our 24/7 radio stations
- **Browse the Store**: Explore our catalog of albums and singles
- **Learn More**: Discover our persona program and the artists behind the music

Tune in, relax, and experience something completely new.

---

*Have questions? Visit our [FAQ page](/faq) or [contact us](/contact) anytime.*',
    'Discover the future of AI-generated music with Reality Radio Network - where technology meets creativity.',
    'Reality Radio Network',
    'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=1200&h=630&fit=crop',
    ARRAY['Welcome', 'AI Music', 'Reality Radio'],
    true,
    '2025-11-15T10:00:00.000Z',
    '2025-11-15T10:00:00.000Z',
    '2025-11-15T10:00:00.000Z'
  )
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  content = EXCLUDED.content,
  excerpt = EXCLUDED.excerpt,
  author = EXCLUDED.author,
  image = EXCLUDED.image,
  tags = EXCLUDED.tags,
  published = EXCLUDED.published,
  published_at = EXCLUDED.published_at,
  updated_at = NOW();

-- =============================================
-- 5. VERIFICAÇÃO DE DADOS INSERIDOS
-- =============================================

-- Contagem de registros inseridos
DO $$
DECLARE
  artist_count INTEGER;
  album_count INTEGER;
  single_count INTEGER;
  blog_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO artist_count FROM artists;
  SELECT COUNT(*) INTO album_count FROM albums;
  SELECT COUNT(*) INTO single_count FROM singles;
  SELECT COUNT(*) INTO blog_count FROM blogs;
  
  RAISE NOTICE '============================================';
  RAISE NOTICE 'MIGRAÇÃO CONCLUÍDA COM SUCESSO!';
  RAISE NOTICE '============================================';
  RAISE NOTICE 'Artistas inseridos: %', artist_count;
  RAISE NOTICE 'Álbuns inseridos: %', album_count;
  RAISE NOTICE 'Singles inseridos: %', single_count;
  RAISE NOTICE 'Blogs inseridos: %', blog_count;
  RAISE NOTICE '============================================';
END $$;

-- Listagem rápida para verificação
SELECT 'ARTISTAS' as tipo, slug, name as titulo FROM artists
UNION ALL
SELECT 'ÁLBUNS' as tipo, slug, title as titulo FROM albums
UNION ALL
SELECT 'BLOGS' as tipo, slug, title as titulo FROM blogs
ORDER BY tipo, slug;
