name: rrn_official
description: Official Reality Radio Network mobile application.
publish_to: 'none'
version: 0.4.1+5

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audio_service: ^0.18.19
  audio_session: ^0.1.21
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  just_audio: ^0.9.42
  shared_preferences: ^2.3.2
  webview_flutter: ^4.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/rrn_app_logo.png
    - assets/radio_static.wav
