name: rrn_official
description: Official Reality Radio Network mobile application.
publish_to: 'none'
version: 0.3.0+3

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audio_session: ^0.1.21
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  just_audio: ^0.9.42
  just_audio_background: ^0.0.1-beta.13
  shared_preferences: ^2.3.2
  webview_flutter: ^4.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/rrn_app_logo.png
    - assets/radio_static.wav
